### ISSUE TITLE
[Suggestion] Number of filtered submissions

### ISSUE THREAD

**Issue by prostagma-fp** [Dri0m/flashpoint-submission-system#45] opened 2021-07-31 23:44 UTC
When you filter submissions to only approved or verified entries for example, there could be a "X submissions found" indicator in the page.

**Comment by Dri0m** [comment] 2021-08-06 19:30
duplicate of https://github.com/Dri0m/flashpoint-submission-system/issues/33

**Closed by Dri0m** 2021-08-06 19:30 UTC
